#!/usr/bin/env python3
"""Make the VO (cuVSLAM) extrinsics from the calibrated panorama extrinsics.

The panorama keeps rig_from_camera in the 'nominal image-up' convention and applies the 180° roll of
the upside-down mount inside its stitch kernel (flip_180). cuVSLAM has no such flip, so for VO the
roll must be baked into the extrinsic itself:

    Q = R_calibrated · Rz180        (Rz180 = 180° about the camera optical axis = diag(-1,-1,1))

i.e. Q is the TRUE rig_from_optical of the physically-inverted sensor — exactly what cuVSLAM needs.
Translations and the IMU pose are unchanged (the roll is per-camera, about the optical axis).

  python3 scripts/calib/fold_roll_for_vo.py \
      --in config/rig/rig_extrinsics_calibrated.yaml \
      --out config/rig/rig_extrinsics_vo.yaml

Re-run this after any recalibration to regenerate the VO file from the new calibrated rotations.
"""
import argparse

import yaml

import extrinsic_calib as ec  # same dir: quat_to_R, R_to_quat, RZ180


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default="config/rig/rig_extrinsics_calibrated.yaml")
    ap.add_argument("--out", default="config/rig/rig_extrinsics_vo.yaml")
    args = ap.parse_args()

    with open(args.inp) as f:
        rig = yaml.safe_load(f)
    out = {k: v for k, v in rig.items()}
    for c, node in rig["cameras"].items():
        R = ec.quat_to_R(node["q_wxyz"])         # nominal rig_from_camera
        Q = R @ ec.RZ180                          # fold the 180 deg optical-axis roll
        out["cameras"][c] = dict(node)
        out["cameras"][c]["q_wxyz"] = [round(float(x), 8) for x in ec.R_to_quat(Q)]
        print(f"  {c}: rolled 180 deg about optical axis -> VO quaternion")
    with open(args.out, "w") as f:
        f.write("# VO (cuVSLAM) extrinsics: CALIBRATED rotations with the 180-deg upside-down-mount\n")
        f.write("# roll FOLDED IN (Q = R_calibrated . Rz180). Generated by scripts/calib/fold_roll_for_vo.py\n")
        f.write(f"# from {args.inp}. Do NOT apply flip_180 with these -- the roll is already baked in.\n")
        yaml.safe_dump(out, f, sort_keys=False, default_flow_style=None)
    print("wrote", args.out)


if __name__ == "__main__":
    main()
